import type { Metadata } from "next"
import localFont from "next/font/local"
import { ModalProvider } from "@/src/common/module/modal-manager"
import MSWComponent from "@/src/mocks/msw-component"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const Regular = localFont({
  src: "../../public/fonts/AppleSDGothicNeo-Regular.woff2",
  display: "swap",
  weight: "400 900",
  variable: "--font-pretendard",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={`md:mx-auto md:max-w-[390px] ${Regular.variable} font-pretendard`}>
        <MSWComponent>
          <ModalProvider>{children}</ModalProvider>
        </MSWComponent>
      </body>
    </html>
  )
}
