import type { Metadata } from "next"
import localFont from "next/font/local"
import { MSWComponent } from "@/src/mocks/msw-component"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const pretendard = localFont({
  src: "../../public/fonts/AppleSDGothicNeo.woff2",
  display: "swap",
  weight: "400 900",
  variable: "--font-pretendard",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={`md:mx-auto md:max-w-[390px] ${pretendard.variable} font-pretendard`}>
        <MSWComponent>{children}</MSWComponent>
      </body>
    </html>
  )
}
